//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.07 at 11:14:55 AM PKT 
//


package com.example.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImportOrderEntryData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImportOrderEntryData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="entrynumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="meta-status" type="{http://www.deichmann.com/xml/hybris/4.1/impex}PositionMetaStatusData"/>
 *         &lt;element name="return-status" type="{http://www.deichmann.com/xml/hybris/4.1/impex}PositionReturnStatusData"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportOrderEntryData", propOrder = {

})
public class ImportOrderEntryData {

    protected int entrynumber;
    @XmlElement(name = "meta-status", required = true)
    protected com.example.entity.PositionMetaStatusData metaStatus;
    @XmlElement(name = "return-status", required = true)
    protected com.example.entity.PositionReturnStatusData returnStatus;

    /**
     * Gets the value of the entrynumber property.
     * 
     */
    public int getEntrynumber() {
        return entrynumber;
    }

    /**
     * Sets the value of the entrynumber property.
     * 
     */
    public void setEntrynumber(int value) {
        this.entrynumber = value;
    }

    /**
     * Gets the value of the metaStatus property.
     * 
     * @return
     *     possible object is
     *     {@link com.example.entity.PositionMetaStatusData }
     *     
     */
    public com.example.entity.PositionMetaStatusData getMetaStatus() {
        return metaStatus;
    }

    /**
     * Sets the value of the metaStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.example.entity.PositionMetaStatusData }
     *     
     */
    public void setMetaStatus(com.example.entity.PositionMetaStatusData value) {
        this.metaStatus = value;
    }

    /**
     * Gets the value of the returnStatus property.
     * 
     * @return
     *     possible object is
     *     {@link com.example.entity.PositionReturnStatusData }
     *     
     */
    public com.example.entity.PositionReturnStatusData getReturnStatus() {
        return returnStatus;
    }

    /**
     * Sets the value of the returnStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.example.entity.PositionReturnStatusData }
     *     
     */
    public void setReturnStatus(com.example.entity.PositionReturnStatusData value) {
        this.returnStatus = value;
    }

}
