//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.07 at 11:14:55 AM PKT 
//


package com.example.entity;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ImportOrderData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImportOrderData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="meta-status" type="{http://www.deichmann.com/xml/hybris/4.1/impex}OrderMetaStatusData"/>
 *         &lt;element name="payment-status" type="{http://www.deichmann.com/xml/hybris/4.1/impex}OrderPaymentStatusData"/>
 *         &lt;element name="shipping-status" type="{http://www.deichmann.com/xml/hybris/4.1/impex}OrderShippingStatusData"/>
 *         &lt;element name="delivery-status" type="{http://www.deichmann.com/xml/hybris/4.1/impex}OrderDeliveryStatusData"/>
 *         &lt;element name="order-entries" type="{http://www.deichmann.com/xml/hybris/4.1/impex}ImportOrderEntriesData"/>
 *         &lt;element name="consignments" type="{http://www.deichmann.com/xml/hybris/4.1/impex}ConsignmentsData" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportOrderData", propOrder = {

})
public class ImportOrderData {

    @XmlElement(required = true)
    protected String code;
    @XmlElement(name = "meta-status", required = true)
    protected OrderMetaStatusData metaStatus;
    @XmlElement(name = "payment-status", required = true)
    protected OrderPaymentStatusData paymentStatus;
    @XmlElement(name = "shipping-status", required = true)
    protected OrderShippingStatusData shippingStatus;
    @XmlElement(name = "delivery-status", required = true)
    protected OrderDeliveryStatusData deliveryStatus;
    @XmlElement(name = "order-entries", required = true)
    protected ImportOrderEntriesData orderEntries;
    protected ConsignmentsData consignments;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the metaStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OrderMetaStatusData }
     *     
     */
    public OrderMetaStatusData getMetaStatus() {
        return metaStatus;
    }

    /**
     * Sets the value of the metaStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderMetaStatusData }
     *     
     */
    public void setMetaStatus(OrderMetaStatusData value) {
        this.metaStatus = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OrderPaymentStatusData }
     *     
     */
    public OrderPaymentStatusData getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderPaymentStatusData }
     *     
     */
    public void setPaymentStatus(OrderPaymentStatusData value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the shippingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OrderShippingStatusData }
     *     
     */
    public OrderShippingStatusData getShippingStatus() {
        return shippingStatus;
    }

    /**
     * Sets the value of the shippingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderShippingStatusData }
     *     
     */
    public void setShippingStatus(OrderShippingStatusData value) {
        this.shippingStatus = value;
    }

    /**
     * Gets the value of the deliveryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDeliveryStatusData }
     *     
     */
    public OrderDeliveryStatusData getDeliveryStatus() {
        return deliveryStatus;
    }

    /**
     * Sets the value of the deliveryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDeliveryStatusData }
     *     
     */
    public void setDeliveryStatus(OrderDeliveryStatusData value) {
        this.deliveryStatus = value;
    }

    /**
     * Gets the value of the orderEntries property.
     * 
     * @return
     *     possible object is
     *     {@link ImportOrderEntriesData }
     *     
     */
    public ImportOrderEntriesData getOrderEntries() {
        return orderEntries;
    }

    /**
     * Sets the value of the orderEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportOrderEntriesData }
     *     
     */
    public void setOrderEntries(ImportOrderEntriesData value) {
        this.orderEntries = value;
    }

    /**
     * Gets the value of the consignments property.
     * 
     * @return
     *     possible object is
     *     {@link ConsignmentsData }
     *     
     */
    public ConsignmentsData getConsignments() {
        return consignments;
    }

    /**
     * Sets the value of the consignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsignmentsData }
     *     
     */
    public void setConsignments(ConsignmentsData value) {
        this.consignments = value;
    }

}
